apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    db: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: database
  name: database
  namespace: user-26
spec:
  containers:
  - name: mysql
    imagePullPolicy: Always
    image: mysql
    ports:
    - name: mysql-port
      containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
          secretKeyRef:
            name: db-secrets
            key: rootPassword
    - name: MYSQL_USER
      valueFrom:
          secretKeyRef:
            name: db-secrets
            key: username
    - name: MYSQL_PASSWORD
      valueFrom:
          secretKeyRef:
            name: db-secrets
            key: password
    - name: MYSQL_DATABASE
      valueFrom:
          secretKeyRef:
            name: db-secrets
            key: database
    resources: 
      limits:
        cpu: "1000m"
        memory: "512Mi"
      requests:
        cpu: "500m"
        memory: "256Mi"
    volumeMounts:
      - mountPath: /etc/secrets/
        name: secrets
    
      - name: mysql-persistent-storage
        mountPath: /var/lib/mysql
      
  volumes:
    - name: secrets
      secret:
        secretName: db-secrets
        defaultMode: 0400
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: mysql-pv-claim  
        

  