apiVersion: v1
kind: Service
metadata:
  labels:
    run: database
  name: db-cluster-ip
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: database
  type: ClusterIP
