apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: ng-svc
    environment: develop
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx