apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: user-26
spec:
  containers:
  - image: nginx:latest
    name: nginx
    ports:
    - containerPort: 80
      name: nginx
    resources: 
      limits:
        cpu: "100m"
        memory: "100Mi"
      requests:
        cpu: "50m"
        memory: "50Mi"
    volumeMounts:
    - mountPath: /etc/nginx/
      name: nginx-conf
    - mountPath: /var/log/nginx
      name: nginx-log
  - image: fluentd:latest
    name: fluentd
    ports:
    - containerPort: 5000
      name: fluentd
    resources: 
      limits:
        cpu: "200m"
        memory: "200Mi"
      requests:
        cpu: "100m"
        memory: "100Mi"
    volumeMounts:
    - mountPath: /etc/fluentd/
      name: fluentd-conf
    - mountPath: /logs
      name: nginx-log
  volumes:
  - name: nginx-conf
    configMap:
      name: nginx-conf
      defaultMode: 256
  - name: fluentd-conf
    configMap:
      name: fluentd-conf
      defaultMode: 256
  - name: nginx-log
    emptyDir: {}
      