apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: wordpress
  name: wordpress
  namespace: user-26
spec:
  containers:
  - image: wordpress:latest
    name: wordpress
    env:
    - name: WORDPRESS_DB_HOST
      value: db-cluster-ip
    - name: WORDPRESS_DB_USER
      valueFrom:
        secretKeyRef:
          name: db-secrets
          key: username
    - name: WORDPRESS_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secrets
          key: password
    - name: WORDPRESS_DB_NAME
      valueFrom:
        secretKeyRef:
          name: db-secrets
          key: database
    ports:
    - containerPort: 80
      name: wordpress
    resources: 
      limits:
        cpu: "1000m"
        memory: "512Mi"
      requests:
        cpu: "500m"
        memory: "256Mi"
    volumeMounts:
      - name: wordpress-persistent-storage
        mountPath: /var/www/html
  volumes:
  - name: wordpress-persistent-storage
    persistentVolumeClaim:
      claimName: wp-pv-claim